### ISSUE TITLE
Make header 30-40 % slimmer

### ISSUE THREAD

**Issue by alexsb** [phovea/phovea_bootstrap_fontawesome#1]
As vertical space is very important, we should reduce the vertical extend significantly.

**Comment by sgratzl** [comment]
still valid?

**Comment by mstreit** [comment]
also done.

example of header from LineUp demo:
![image](https://cloud.githubusercontent.com/assets/4129755/20217927/880c0c20-a822-11e6-9c4b-55fcaa8cae29.png)
