### ISSUE TITLE
Improve About Dialog

### ISSUE THREAD

**Issue by sgratzl** [phovea/phovea_bootstrap_fontawesome#7]
include the phovea/generator-phovea#30 collected information to present details about the current setup

**Comment by sgratzl** [comment]
what about server state and plugin version?

**Comment by sgratzl** [comment]
current version, if build info is available:

![2016-11-14 21_37_11-importer test](https://cloud.githubusercontent.com/assets/4129778/20281906/ada5a56c-aab2-11e6-849b-9b92cf18f75a.png)

**Comment by sgratzl** [comment]
additional useful information
 * current web browser version
 * operation system
 * window resolution?

see also http://www.alanwood.net/demos/browserinfo.html

**Comment by thinkh** [comment]
First version is merged by pull request https://github.com/phovea/phovea_bootstrap_fontawesome/pull/8.
