### ISSUE TITLE
Webpack build error modal does not exist on type JQuery

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_bootstrap_fontawesome#9]
When building a phovea application in src/dialogs I get the following error:

```
ERROR in [default] D:\dev\repos\phovea\ueber_context\phovea_bootstrap_fontawesome\src\dialogs.ts:40:21
Property 'modal' does not exist on type 'JQuery'.

ERROR in [default] D:\dev\repos\phovea\ueber_context\phovea_bootstrap_fontawesome\src\dialogs.ts:44:21
Property 'modal' does not exist on type 'JQuery'.
```

**Comment by sgratzl** [comment]
already fixed in https://github.com/phovea/phovea_bootstrap_fontawesome/pull/8

**Comment by thinkh** [comment]
Resolved by merging https://github.com/phovea/phovea_d3/pull/6, https://github.com/phovea/phovea_bootstrap_fontawesome/pull/8, and https://github.com/phovea/generator-phovea/pull/33.
